# Generated by Django 2.0.7 on 2022-02-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180725_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userask',
            name='name',
            field=models.CharField(error_messages={'blank': '用户名不能为空'}, help_text='此字段不为空', max_length=20, verbose_name='姓名'),
        ),
    ]
